config/routes.rb
MovieRecommendation::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  resources :users, :only => [:show] do
    resources :movies do
      member do
        post :vote_up
      end
    end
  end

  get "home/index"

    root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      can :update, User, :id => user.id
      can :update, Movie, :user_id => user.id 
      can :destroy, Movie, :user_id => user.id
      can :read, :all


    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name

  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :year, :genre_ids
  attr_accessor :genre_ids

  acts_as_voteable

  has_many :movie_genres, dependent: :destroy
  has_many :genres, through: :movie_genres

  belongs_to :user

  validates :title, :year, presence: true

  def display_year
    year.to_date.year if year.present?
  end

  def display_genres
    genres.collect(&:name).to_a.join(', ')
  end

  def display_title
    title.to_s.titleize
  end

  def add_genres(genre_ids)
    return if genre_ids.blank?
    self.genres.delete_all
    genre_ids.each do |genre_id|
      next if genre_id.blank?
      self.movie_genres.create(:movie_id => self.id, :genre_id => genre_id)
    end
  end
end

app/models/movie_genre.rb
class MovieGenre < ActiveRecord::Base
  attr_accessible :genre_id, :movie_id

  belongs_to :movie
  belongs_to :genre
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  acts_as_voter

  validates :name, :presence => true

  has_many :movies

  def display_name
    name.to_s.titleize
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :get_user
  before_filter :get_movie, :only => [:show, :update, :edit, :destroy, :vote_up]
  before_filter :authenticate_user!
  def index
    @movies = @user.movies.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  def edit
    @movie = @user.movies.find(params[:id])
  end

  def create
    @movie = @user.movies.new(params[:movie])

    respond_to do |format|
      if @movie.save
        @movie.add_genres(params[:movie][:genre_ids])
        format.html { redirect_to [@user, @movie], notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        @movie.add_genres(params[:movie][:genre_ids])
        format.html { redirect_to [@user, @movie], notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  def vote_up
    if current_user.present?
       if current_user.voted_for?(@movie)
        current_user.unvote_for(@movie)
      else
        current_user.vote_exclusively_for(@movie)
      end
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def get_user
    @user = User.find params[:user_id]
  end

  def get_movie
    @movie = Movie.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:show]
  before_filter :authenticate_user!

  def show
    @movies = @user.movies
    @liked_movies = User.first.votes.collect(&:voteable)
  end

  private

  def get_user
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def is_voted_for?(votable)
    return "<span class='label label-info'><i class='icon-thumbs-up' class='gray_thumb'></i> Like</span>".html_safe if current_user.blank?
    return "<span class='label label-success'><i class='icon-thumbs-up'></i> Liked</span>".html_safe if current_user.voted_for?(votable)
    "<span class='label label-info'><i class='icon-thumbs-up'></i> Like</span>".html_safe
  end

  def is_voted_against?(votable)
    return "<span class='label label-warning'><i class='icon-thumbs-down'></i> Dislike</span>".html_safe if current_user.blank?
    return "<span class='label label-important'><i class='icon-thumbs-down'></i> Disliked</span>".html_safe if current_user.voted_against?(votable)
    "<span class='label label-warning'><i class='icon-thumbs-down'></i> Dislike</span>".html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Epic Movies</h1>
<%= render "movies/movies", :movies => @movies %>

app/views/layouts/_body.html.erb
<div class="container">
  <%= render :partial => "layouts/messages" %>
  <div class="row-fluid">
    <div class="span12">
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <hr/>
  <footer>
    <div class="span12 centered margin-bottom-20px">
      &copy; Test
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Movie Mania", root_path, :class=> 'brand' %>
      <div class="nav-collapse in collapse">
        <ul class="nav">
          <li><%= link_to 'Movies', root_path %></li>
        </ul>

        <div class="nav pull-right">
          <% unless user_signed_in? %>
            <div class="btn-group login-group">
              <%= link_to "Login", new_user_session_path, :class => 'btn btn-info' %>
              <%= link_to "Register", new_user_registration_path, :class => 'btn btn-info'%>
            </div>
          <% else %>
            <li>
              <%= link_to "Add Movie", new_user_movie_path(current_user) %>
            </li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%= current_user.display_name %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Account", current_user %>
                </li>
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path(current_user) %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                </li>
              </ul>
            </li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div id="messages" class="">
  <div class="container">
    <% flash.each_with_index do |(k,v),i| %>
      <div id="message-<%= i %>" class="actual-message">
        <div class="alert alert-<%= k.to_s.sub('_stay', '') %>">
          <a data-dismiss="alert" class="close btn btn btn-danger"><i class="icon-remove"></i></a>
          <h4 class="alert-heading"><%= k.to_s.sub('_stay', '').titleize %>!</h4>
          <% if v.is_a?(Array) %>
            <ul>
              <% v.each do |vv| %>
                <li><%= vv %></li>
              <% end %>
            </ul>
          <% else %>
            <%= raw v %>
          <% end %>
        </div>
      </div>

      <% unless k.to_s.index('_stay') %>
        <script>
            setTimeout("$('#message-<%= i %>').fadeOut('slow');", 5000);
        </script>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieRecommendation</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render :partial => "layouts/header" %>
    <%= render :partial => "layouts/body" %>
    <%= render :partial => "layouts/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for([@user, @movie]) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :genre_ids, "Select Genres" %><br />
    <%= f.select :genre_ids, Genre.all.collect {|x| [x.name, x.id]}, {}, include_blank: false, :multiple => true %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :year, {:start_year => Time.now.year, :end_year => Time.now.year - 95, :discard_day => true, :discard_month => true}, :selected => @movie.year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_movie_links.html.erb
<div class="row-fluid">
  <% if can? :update, movie %>
    <%= link_to "Edit", edit_user_movie_path(current_user, movie) %>
  <% end %>
  |
  <% if can? :destroy, movie %>
    <%= link_to "Destroy", user_movie_path(current_user, movie), :method => :delete %>
  <% end %>
</div>

app/views/movies/_movies.html.erb
<ul class="thumbnails">
<% movies.each do |movie| %>
  <li>
    <div class="thumbnail">
      <h3><%= movie.display_title %></h3>
      <div class="row-fluid">
        <div class="span2">
          Year: <%= movie.display_year %>
        </div>
        <div class="span10">
          Genres: <%= movie.display_genres %>
        </div>
      </div>

      <div class="row-fluid like-<%= movie.id %>">
        <div class="span10">
          <% if user_signed_in? %>
            <%= link_to vote_up_user_movie_path(current_user, movie), :remote => true, :method => :post do %>
              <%= is_voted_for?(movie) %> <%= movie.votes_for %>
            <% end %>
          <% else %>
            <span class="label label-inverse"><%= movie.votes_for %> likes</span>
          <% end %>
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="row-fluid">
          <%= render "movies/movie_links", :movie => movie %>
        </div>
      <% end %>


    </div>
  </li>
<% end %>

app/views/movies/_vote_up.html.erb
<div class="row-fluid like-<%= @movie.id %>">
  <div class="span3">
    <%= link_to vote_up_user_movie_path(current_user, @movie), :remote => true, :method => :post do %>
      <%= is_voted_for?(@movie) %> <%= @movie.votes_for %>
    <% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @movie] %> |
<%= link_to 'Back', user_movies_path(@user) %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= render "movies", :movies => @movies %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', user_movies_path(@user) %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.display_year %>
</p>

<p>
  <b>Genres:</b>
  <%= @movie.display_genres %>
</p>

<%= link_to 'Edit', edit_user_movie_path(@user, @movie) %> |
<%= link_to 'Back', user_movies_path(@user) %>

app/views/movies/vote_up.js.erb
$(".like-<%= @movie.id %>").html("<%= raw escape_javascript(render :partial => 'vote_up') %>");

app/views/users/show.html.erb
<h1><%= @user.display_name %></h1>

<div class="row-fluid">
  <ul class="nav nav-tabs">
    <li><a href="#added" data-toggle="tab">Added Movies</a></li>
    <li><a href="#liked" data-toggle="tab">Liked Movies</a></li>
  </ul>
  <div class="tab-content">
    <div id="added" class="tab-pane active">
      <%= render "movies/movies", :movies => @movies %>
    </div>
    <div id="liked" class="tab-pane">
      qwqe
      <%= render "movies/movies", :movies => @liked_movies %>
    </div>
  </div>
</div>